// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.tsz.grpc.route.protocol;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.tsz.grpc.route.protocol.Point getLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.tsz.grpc.route.protocol.PointOrBuilder getLoOrBuilder();

  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.tsz.grpc.route.protocol.Point getHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.tsz.grpc.route.protocol.PointOrBuilder getHiOrBuilder();
}
