// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.tsz.grpc.route.protocol;

public interface RouteSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 point_count = 1;</code>
   */
  int getPointCount();

  /**
   * <code>int32 feature_count = 2;</code>
   */
  int getFeatureCount();

  /**
   * <code>int32 distance = 3;</code>
   */
  int getDistance();

  /**
   * <code>int32 elapsed_time = 4;</code>
   */
  int getElapsedTime();
}
